local_rank: 0

load_path: null
rng_seed: 0

mode: train # set to test in evaluation only mode
logname: null

# this project supports wandb, please check their documentation for details: https://docs.wandb.ai/
wandb:
  entity: null
  use_wandb: True
